const FontConfig = {
  Lato: {
    thinItalic: 'Lato-ThinItalic',
    thin: 'Lato-Thin',
    regular: 'Lato-Regular',
    lightItalic: 'Lato-LightItalic',
    light: 'Lato-Light',
    italic: 'Lato-Italic',
    boldItalic: 'Lato-BoldItalic',
    bold: 'Lato-Bold',
    blackItalic: 'Lato-BlackItalic',
    black: 'Lato-Black',
  },
  NunitoSans: {
    black: 'NunitoSans-Black',
    blackItalic: 'NunitoSans-BlackItalic',
    bold: 'NunitoSans-Bold',
    boldItalic: 'NunitoSans-BoldItalic',
    extraBold: 'NunitoSans-ExtraBold',
    extraBoldItalic: 'NunitoSans-ExtraBoldItalic',
    extraLight: 'NunitoSans-ExtraLight',
    extraLightItalic: 'NunitoSans-ExtraLightItalic',
    italic: 'NunitoSans-Italic',
    lightItalic: 'NunitoSans-LightItalic',
    regular: 'NunitoSans-Regular',
    light: 'NunitoSans-Light',
    semiBold: 'NunitoSans-SemiBold',
    semiBoldItalic: 'NunitoSans-SemiBoldItalic',
  },
  Rubik: {
    black: 'Rubik-Black',
    blackItalic: 'Rubik-BlackItalic',
    bold: 'Rubik-Bold',
    boldItalic: 'Rubik-BoldItalic',
    extraBold: 'Rubik-ExtraBold',
    extraBoldItalic: 'Rubik-ExtraBoldItalic',
    italic: 'Rubik-Italic',
    light: 'Rubik-Light',
    lightItalic: 'Rubik-LightItalic',
    medium: 'Rubik-Medium',
    mediumItalic: 'Rubik-MediumItalic',
    regular: 'Rubik-Regular',
    semiBold: 'Rubik-SemiBold',
    semiBoldItalic: 'Rubik-SemiBoldItalic',
  },
};

export default FontConfig;
